name: baitek
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  shimmer: ^3.0.0
  # flashy_tab_bar: ^0.0.3
  iconsax: ^0.0.8
  dio: ^5.3.2
  concentric_transition: ^1.0.1
  odometer: ^3.0.0
  vertical_card_pager: ^1.5.0
  loading_indicator: ^3.0.2
  animate_do: ^3.0.2
  flutter_youtube_view: ^2.0.2
  flutter_verification_code: ^1.1.0
  liquid_swipe: ^3.1.0
  intl_phone_number_input: ^0.7.0+2
  elastic_drawer: ^2.0.1
  bouncing_widget: ^2.0.0
  bottom_navy_bar: ^6.0.0
  salomon_bottom_bar: ^3.1.0
  avatar_glow: ^2.0.2
  carousel_slider: ^4.0.0
  google_fonts: ^5.1.0
  fl_chart: ^0.63.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
